
name: pwj_actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up gradle
#          uses: actions/setup-java@v2
          with:
            cache: gradle
      - name: Build
        run: ./gradlew assembleRelease
