
name: pwj_actions
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

env:
PROJECT_PATH: FileShared

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties')}}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        working-directory: ${{ env.PROJECT_PATH }}
        run: ./gradlew assembleRelease
