
name: pwj_actions
on:
  push:
    paths:
      - '.github/workflows/pwj_actions.yaml'
      - 'FileShared/**'
    branches:
      - '*'
  pull_request:
    paths:
      - '.github/workflows/pwj_actions.yaml'
      - 'FileShared/**'
    branches:
      - master

env:
  PROJECT_PATH: FileShared

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle

        working-directory: ${{ env.PROJECT_PATH }}
        run: ./gradlew assembleRelease
